5740 ^package-main WIP fill in missing kfocus-btool components, integrate with focusrx

diff --git a/package-main/usr/lib/kfocus/bin/kfocus-btool b/package-main/usr/lib/kfocus/bin/kfocus-btool
--- a/package-main/usr/lib/kfocus/bin/kfocus-btool
+++ b/package-main/usr/lib/kfocus/bin/kfocus-btool
@@ -30,8 +30,68 @@ _importCommonFn () {
 
 ## BEGIN _assignGlobalUiVarsFn {
 _assignGlobalUiVarsFn () {
-  # TODO: Finish filling in UI vars.
-  _noUpgradeAvailableMsg='No BIOS upgrades are available for this system.'
+  _windowTitle='Focus Bios Tool';
+
+  _dlBiosNotAvailableMsg='No BIOS downloads are available for this system.';
+
+  # XSMC is a placeholder for "system model code", kept short to avoid
+  # wrapping issues
+  _dlBiosMatchesMsg="$(cat <<EOF
+Your system's BIOS is fully up-to-date.
+
+If you have other XSMC systems that you would like to upgrade the BIOS of,
+you can download the most recent BIOS upgrade and flash it to a USB stick.
+Would you like to do this now?
+EOF
+  )";
+
+  _dlBiosGreaterOptionalUpgradeMsg="$(cat <<EOF
+Your system's BIOS is sufficiently up-to-date. A newer BIOS is available, but
+it is not critical to install the update.
+
+Would you like to download the newest XSMC BIOS and flash it to a USB stick?
+EOF
+  )";
+
+  _dlBiosGreaterRequiredUpgradeMsg="$(cat <<EOF
+Your system's BIOS is not up-to-date. A newer BIOS is available that will
+resolve known bugs on your system.
+
+Would you like to download the newest XSMC BIOS and flash it to a USB stick?
+EOF
+  )";
+
+  _dlBiosLesserRequiredDowngradeMsg="$(cat <<EOF
+Your system's BIOS is newer than the recommended version. An older version is
+available that will resolve known bugs on your system.
+
+Would you like to download the recommended XSMC BIOS and flash it to a USB
+stick?
+EOF
+  )";
+
+  _insertUsbMsg="$(cat <<EOF
+Please insert an 8+ GB USB on which to install the BIOS upgrade. Kubuntu Focus
+systems come with a USB drive that can be used for this purpose. IGNORE ANY
+OFFERS by the OS to 'mount' or 'open' any files or folders on the drive.
+
+IMPORTANT: THIS TOOL WILL REMOVE ALL DATA FROM THE USB DRIVE. As a precaution,
+make sure you back up any data from the USB and system drives before
+proceeding.
+EOF
+  )";
+
+  _biosDownloadMsg='Downloading BIOS...';
+  _biosDownloadEndMsg='BIOS download complete.';
+
+  _biosFlashMsg='Flashing BIOS to USB stick...';
+  _biosFlashEndMsg='Finished flashing BIOS to USB stick.';
+  _biosFlashErrMsg='Failed to flash BIOS to USB stick!';
+
+  _cancelUpgradeMsg='BIOS upgrade cancelled.';
+
+  _toolEndMsg='The Focus Bios Tool has finished running.';
+  _toolEndErrMsg='The Focus Bios Tool encountered errors and has failed.';
 }
 ## . END _assignGlobalUiVarsFn }
 
@@ -68,30 +128,12 @@ _cleanupFn () {
 ## BEGIN _exitCleanFn {
 _exitCleanFn () {
   declare _int;
-  _int="$(_echoIntFn "${1:-0}")";
+  _int="$(_cm2EchoIntFn "${1:-0}")";
   trap '' EXIT; # Ignore EXIT signal. 'trap - EXIT' would revert to default.
   _cleanupFn;
   exit "${_int}";
 }
 ## . END _exitCleanFn }
-
-## BEGIN _testVersionFn {
-# Summary   : _testVersionFn version1 version2
-# Purpose   : Tests if version1 is newer than version 2.
-# Example   : _testVersionFn '1.07.12MIN29' '1.07.07MIN29'
-# Arguments : version1 and version2, both of which are strings.
-# Globals   : none
-# Outputs   : none
-# Returns   : 0 if version1 sorts before version2 when using a version sort, 1
-#             otherwise.
-#
-_testVersionFn () {
-  declare _v1 _v2;
-  _v1="${1:-}"; _v2="${2:-}";
-  [ "$_v1" = "$_v2" ] && return 1;
-  [ "$_v1" = "$(echo -e "$_v1\n$_v2" |sort -rV |head -n1)" ];
-}
-## . END _testVersionFn }
 
 ## BEGIN _checkRootFn {
 _checkRootFn () {
@@ -116,10 +158,10 @@ _echoHelpFn () {
 
 ## BEGIN _loadConfigFn {
 _loadConfigFn () {
-  declare _model_str _config_file;
+  declare _config_file;
 
-  _model_str="$(_cm2EchoModelStrFn 'code')";
-  _config_file="${_binDir}/kfocus-btool.d/${_model_str}.source"
+  _modelStr="$(_cm2EchoModelStrFn 'code')";
+  _config_file="${_binDir}/kfocus-btool.d/${_modelStr}.source"
 
   # If no configuration found for this model, return and leave config-specific
   # globals empty
@@ -129,7 +171,7 @@ _loadConfigFn () {
 
   # shellcheck source=kfocus-btool.d/m2g6.source
   source "${_config_file}" || {
-    _cm2ErrStrFn "Could not source config file for |${_model_str}|!";
+    _cm2ErrStrFn "Could not source config file for |${_modelStr}|!";
     exit 1;
   }
 }
@@ -166,9 +208,9 @@ _detectUpgradeStatusFn () {
     return 0;
   fi
 
-  if _testVersionFn "${_availBiosVersion}" "${_current_bios_version}"; then
-    if [ "${_currrent_bios_version}" = "${_minBiosVersion}" ] \
-      || _testVersionFn "${_current_bios_version}" "${_minBiosVersion}"; then
+  if _cm2TestVersFn "${_availBiosVersion}" "${_current_bios_version}"; then
+    if [ "${_current_bios_version}" = "${_minBiosVersion}" ] \
+      || _cm2TestVersFn "${_current_bios_version}" "${_minBiosVersion}"; then
       echo 'dl_bios_greater_optional_upgrade';
     else
       echo 'dl_bios_greater_required_upgrade';
@@ -186,9 +228,225 @@ _detectUpgradeStatusFn () {
 }
 ## . END _detectUpgradeStatusFn }
 
+## BEGIN _downloadBiosFn {
+_downloadBiosFn () {
+  _cm2EchoFn "${_biosDownloadMsg}";
+  _tmpBiosFile="${_tmpDir}/kfocus-bios-download";
+  # TODO: Do we really want to use -q (quiet) here?
+  wget -q "${_biosDownloadUrl}" -O "${_tmpBiosFile}" || return 1;
+  _cm2EchoFn "${_biosDownloadEndMsg}";
+}
+## . END _downloadBiosFn }
+
+## BEGIN _selectDiskFn {
+# Returns: 0 on success, 1 on failure, 2 if the user cancels the upgrade
+_selectDiskFn () {
+  declare _found_list _mount_str _block_list _dev_file _byte_int _mib_int \
+    _trans_key _match_str _example_str _msg _line _idx _bit_list _info_str \
+    _reply _pick_idx;
+
+  while true; do # begin scan-block
+    _cm2EchoFn 'Scan USB Drives...';
+    _found_list=();
+    _mount_str="$(cat /proc/mounts)";
+    mapfile -t _block_list < <(
+      find /dev/ -maxdepth 1 -mindepth 1 -type b -name 'sd[a-z]' | sort
+    );
+    for _dev_file in "${_block_list[@]}"; do # begin dev-block
+      _byte_int="$(blockdev --getsize64 "${_dev_file}")";
+      _mib_int="$(( _byte_int / _mibBytes ))";
+      _trans_key="$(lsblk -ndo tran "${_dev_file}")";
+      if [ "${_trans_key}" != 'usb' ]; then continue; fi # on dev-block
+
+      _cm2EchoFn "* Found USB Drive |${_dev_file}|";
+      _match_str="$(
+        grep "^${_dev_file}" <<< "${_mount_str}" | cut -f2 -d' '
+      )";
+
+      if [ "${_mib_int}" = '0' ]; then
+        _cm2EchoFn '  Device has invalid size (0.00 GiB).';
+        continue; # on dev-block
+      fi
+
+      if [ -n "${_match_str}" ]; then
+        _cm2EchoFn "  Device is mounted at |${_match_str}|, cannot use";
+        _example_str="      sudo umount ${_match_str}";
+        _msg="$(cat <<EOF
+  If you wish to use this device:
+    A. IN ANOTHER TERMINAL, unmount the partition(s) like so:
+${_example_str}
+    B. If any partition cannot be unmounted because it is "busy", close
+      any file manager or terminal that is using the file system and try
+      again.
+    C. Select "rescan" from the options below to proceed.
+EOF
+        )";
+        _cm2EchoFn "${_msg}";
+        continue;
+      fi
+
+      _found_list+=( "${_dev_file};${_mib_int}" );
+    done # end dev-block
+
+    _cm2EchoFn 'Scan complete.';
+
+    _cm2EchoFn 'Choose an action:';
+    _cm2EchoFn '=================';
+    _idx=0;
+    for _line in "${_found_list[@]}"; do
+      IFS=';' read -r -a _bit_list <<< "${_line}";
+      printf -v _info_str '%s %3.2f GB' "${_bit_list[0]}" "$(\
+        bc <<< "scale=2; ${_bit_list[1]} / 1024"
+      )";
+      _cm2EchoFn "${_idx}. Install BIOS upgrade to ${_info_str}.";
+      (( _idx++ )) || true;
+    done
+    _cm2EchoFn "${_idx}. Rescan USB storage devices.";
+    (( _idx++ )) || true;
+    _cm2EchoFn "${_idx}. Exit without changing anything.";
+    _cm2EchoFn '';
+
+    _cm2NechoFn "Enter action id (${_idx}): ";
+    read -r _reply;
+    _cm2EchoFn '--------------------------------';
+    _pick_idx="$(_echoIntFn "${_reply:-${_idx}}")";
+
+    if (( _pick_idx == _idx )); then
+      _cm2EchoFn "${_cancelUpgradeMsg}";
+      return 2;
+    fi
+    if (( _pick_idx == (_idx - 1) )); then continue; fi # on scan-block
+    if (( _pick_idx < 0 || _pick_idx >= _idx )); then
+      _cm2EchoFn "Please enter 0 through ${_idx}. Rescanning...";
+      continue; # on scan-block
+    fi
+
+    IFS=';' read -r -a _bit_list <<< "${_found_list[${_pick_idx}]}";
+    printf -v _info_str '%s %3.2f GB' "${_bit_list[0]}" "$(\
+      bc <<< "scale=2; ${_bit_list[1]} / 1024"
+    )";
+
+    if (( _bit_list[1] > _32gibMibs )); then
+      _msg="$(cat <<EOF
+${_info_str} is larger than 32 GB. Are you sure you want to overwrite?
+Please enter "overwrite" to confirm >
+EOF
+      )";
+      _cm2NechoFn "${_msg} ";
+      read -r _reply;
+      _cm2EchoFn '';
+
+      if [ "${_reply:-}" != 'overwrite' ]; then
+        # TODO: Might be better to rescan rather than abort here
+        _cm2EchoFn "${_cancelUpgradeMsg}";
+        return 2;
+      fi
+    fi
+    _msg="$(cat <<EOF
+About to OVERWRITE USB drive ${_info_str} with the BIOS upgrade. All data
+on this drive will be lost.
+
+If this is correct, continue, otherwise press Ctrl+C to abort.
+EOF
+    )";
+    _cm2PromptUserFn "${_msg}" "${_windowTitle}" 'p'
+    break; # Exit scan-block, always
+  done # End scan-block
+
+  _targetUsbDev="${_bit_list[0]}";
+}
+## . END _selectDiskFn }
+
+## BEGIN _beginUpgradeFn {
+_beginUpgradeFn () {
+  declare _return_int;
+  _tmpDir="$(mktemp -d)";
+
+  _cm2PromptUserFn "${_insertUsbMsg}" "${_windowTitle}" 'p';
+
+  _downloadBiosFn || return 1;
+
+  _selectDiskFn || return 1;
+  _return_int="$?";
+  if [ "${_return_int}" = '1' ]; then
+    return 1;
+  elif [ "${_return_int}" = '2' ]; then
+    return 0;
+  fi
+
+  _cm2EchoFn "${_biosFlashMsg}";
+  _flashBiosFn || {
+    _cm2EchoFn "${_biosFlashErrMsg}"
+    return 1;
+  }
+  _cm2EchoFn "${_biosFlashEndMsg}";
+
+  _cm2EchoFn "${_installStepsMsg}";
+}
+## . END _beginUpgradeFn }
+
 ## BEGIN _tryOfferUpgradeFn {
 _tryOfferUpgradeFn () {
-  true;
+  declare _msg _is_error_hit _reply _upgrade_status_str;
+
+  _is_error_hit='n';
+  _msg="$(cat <<EOF
+ _____                      ____  _             _____           _
+|  ___|__   ___ _   _ ___  | __ )(_) ___  ___  |_   _|__   ___ | |
+| |_ / _ \ / __| | | / __| |  _ \| |/ _ \/ __|   | |/ _ \ / _ \| |
+|  _| (_) | (__| |_| \__ \ | |_) | | (_) \__ \   | | (_) | (_) | |
+|_|  \___/ \___|\__,_|___/ |____/|_|\___/|___/   |_|\___/ \___/|_|
+
+EOF
+  )";
+  _cm2EchoFn "${_msg}";
+
+  _upgrade_status_str="$(_detectUpgradeStatusFn)";
+  case "${_upgrade_status_str}" in
+    'dl_bios_not_available')
+      _cm2EchoFn "${_dlBiosNotAvailableMsg}";
+      ;;
+    'dl_bios_matches')
+      _msg="${_dlBiosMatchesMsg//XSMC/"${_modelStr}"}";
+      _reply="$(_cm2PromptUserFn "${_msg}" "${_windowTitle}" 'a')";
+      if [ "${_reply}" = 'y' ]; then
+        _beginUpgradeFn || _is_error_hit='y';
+      fi
+      ;;
+    'dl_bios_greater_optional_upgrade')
+      _msg="${_dlBiosGreaterOptionalUpgradeMsg//XSMC/"${_modelStr}"}";
+      _reply="$(_cm2PromptUserFn "${_msg}" "${_windowTitle}" 'a')";
+      if [ "${_reply}" = 'y' ] ; then
+        _beginUpgradeFn || _is_error_hit='y';
+      fi
+      ;;
+    'dl_bios_greater_required_upgrade')
+      _msg="${_dlBiosGreaterRequiredUpgradeMsg//XSMC/"${_modelStr}"}";
+      _reply="$(_cm2PromptUserFn "${_msg}" "${_windowTitle}" 'a')";
+      if [ "${_reply}" = 'y' ] ; then
+        _beginUpgradeFn || _is_error_hit='y';
+      fi
+      ;;
+    'dl_bios_lesser_required_downgrade')
+      _msg="${_dlBiosLesserRequiredDowngradeMsg//XSMC/"${_modelStr}"}";
+      _reply="$(_cm2PromptUserFn "${_msg}" "${_windowTitle}" 'a')";
+      if [ "${_reply}" = 'y' ] ; then
+        _beginUpgradeFn || _is_error_hit='y';
+      fi
+      ;;
+    *)
+      _cm2ErrStrFn "Unexpected upgrade status |${_upgrade_status_str}| hit!";
+      _is_error_hit='y';
+      ;;
+  esac
+
+  if [ "${_is_error_hit}" = 'y' ]; then
+    _cm2PromptUserFn "${_toolEndErrMsg}" "${_windowTitle}" 'p';
+    _exitCleanFn 1;
+  else
+    _cm2PromptUserFn "${_toolEndMsg}" "${_windowTitle}" 'p';
+    _exitCleanFn;
+  fi
 }
 ## . END _tryOfferUpgradeFn }
 
@@ -215,16 +473,27 @@ _mainFn () {
 
 ## BEGIN Declare global variables {
 declare _binName _binDir _baseDir _baseName _tmpDir _tmpBiosFile \
-  _usbTmpMountDir _dmiDecodeExe _minBiosVersion _availBiosVersion \
-  _installStepsMsg _noUpgradeAvailableMsg;
+  _usbTmpMountDir _modelStr _targetUsbDev _mibBytes _32gibMibs _dmiDecodeExe \
+  _minBiosVersion _availBiosVersion _biosDownloadUrl _installStepsMsg \
+  _windowTitle _dlBiosNotAvailableMsg _dlBiosMatchesMsg \
+  _dlBiosGreaterOptionalUpgradeMsg _dlBiosGreaterRequiredUpgradeMsg \
+  _dlBiosLesserRequiredDowngradeMsg _insertUsbMsg _biosDownloadMsg \
+  _biosDownloadEndMsg _biosFlashMsg _biosFlashEndMsg _biosFlashErrMsg \
+  _cancelUpgradeMsg _toolEndMsg _toolEndErrMsg;
 
 _tmpDir='';
 _tmpBiosFile='';
 _usbTmpMountDir='';
+_modelStr='';
+_targetUsbDev='';
+
+_mibBytes=1048576;
+_32gibMibs=32768;
 
 # These variables will be filled in by the config scripts under kfocus-btool.d.
 _minBiosVersion='';
 _availBiosVersion='';
+_biosDownloadUrl='';
 _installStepsMsg='';
 ## . END Declare global variables }
 
@@ -243,6 +512,9 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   fi
 
   _assignGlobalUiVarsFn;
+
+  # Only prompt using the terminal
+  _cm2IsTty='y';
 
   _mainFn "$@";
 fi
