5845 ^kfocus-focusrx add refresh rate warnings and fixes for m2g6/zrg1

diff --git a/package-main/usr/lib/kfocus/bin/kfocus-focusrx b/package-main/usr/lib/kfocus/bin/kfocus-focusrx
--- a/package-main/usr/lib/kfocus/bin/kfocus-focusrx
+++ b/package-main/usr/lib/kfocus/bin/kfocus-focusrx
@@ -406,6 +406,136 @@ _chkNvPMizerFn () {
 }
 ## . END _chkNvPMizerFn }
 
+## BEGIN _chkDispRefreshFn {
+_chkDispRefreshFn () {
+  declare _title _win_title _prompt_msg _kscreen_doctor_report \
+    _internal_disp_name _nag_name _init_nag_count _warn_nag_count;
+
+  _init_nag_count='1';
+  _warn_nag_count='6';
+  _nag_name='kfocus-disphz_count';
+
+  # Skip if not on m2g6 or zrg1.
+  [[ "$(_cm2EchoModelStrFn 'config_code')" =~ ^(m2g6|zrg1)$ ]] || return;
+  # Skip if required tool not installed.
+  [ -z "${_kscreenDoctorExe}" ] && return;
+
+  _title='Configure display refresh';
+  _cm2SetMsgFn "${_title}";
+  _win_title="${_rootTitle}: ${_title}";
+
+  # Calculate laptop display name
+  _kscreen_doctor_report="$("${_kscreenDoctorExe}" -o)";
+  _internal_disp_name="$(
+    ansi2txt <<< "${_kscreen_doctor_report}" \
+      | cut -d' ' -f3-5 \
+      | grep 'eDP.* enabled connected' \
+      | cut -d' ' -f1 \
+      | head -n1
+  )";
+  if [ -z "${_internal_disp_name}" ]; then
+    _cm2WarnStrFn 'Laptop display not found. Will try again next login.';
+    _cm2WarnFn;
+    return;
+  fi
+
+  # Check nag count
+  if _nag_msg="$(
+    _testNagCountFn 'check' "${_nag_name}" "${_init_nag_count}"
+  )"; then
+    # Set display to 60 Hz and return without prompting the user.
+    if "${_kscreenDoctorExe}" "output.${_internal_disp_name}.mode.2560x1600@60";
+      then _testNagCountFn 'fill' "${_nag_name}" "${_init_nag_count}";
+      _cm2SucFn;
+    else
+      # We do not increment the nag count here so that we will try to set the
+      # mode again later if this fails.
+      _cm2WarnStrFn 'Could not set screen mode. Will try again next login';
+      _cm2WarnFn;
+    fi
+    return;
+  fi
+
+  # Skip if screen is already set to the desired mode
+  if grep " ${_internal_disp_name} " <<< "${_kscreen_doctor_report}" \
+    | grep -q '2560x1600@60\*'; then
+    #_testNagCountFn 'fill' "${_nag_name}" "${_max_nag_count}";
+    _cm2SucStrFn 'Desired screen refresh already set.';
+    _cm2SucFn;
+    return;
+  fi
+
+  # Set display refresh rate to 240 Hz if it is at 300 Hz
+  if grep " ${_internal_disp_name} " <<< "${_kscreen_doctor_report}" \
+    | grep -q '2560x1600@300\*'; then
+    _prompt_msg="$(cat <<EOF
+${_cm2HtmBeginStr}
+${_cm2HtmH3Str}${_title}</h3>
+
+<p><b>Setting screen refresh rate to 240 Hz for better stability.</b></p>
+
+${_cm2HtmPStr}Laptop display refresh rates greater than 240 Hz are<br>
+unsupported and may cause system crashes or other<br>
+undesirable behavior.</p>
+
+${_cm2HtmPStr}If you are using multiple monitors, you may wish to<br>
+further reduce the laptop display refresh rate to 60 Hz.<br>
+This provides more display bandwidth for external<br>
+displays.</p>
+
+${_cm2HtmPStr}You may change the refresh rate later using <code>System<br>
+Settings &gt; Display and Monitor &gt; Display<br>
+Configuration &gt; Refresh Rate</code>.</p>${_cm2HtmEndStr}
+EOF
+    )";
+
+    _cm2PromptUserFn "${_prompt_msg}" "${_win_title}";
+
+    if "${_kscreenDoctorExe}" \
+      "output.${_internal_disp_name}.mode.2560x1600@240"; then\
+      _testNagCountFn 'fill' "${_nag_name}" "${_warn_nag_count}";
+      _cm2SucFn;
+    else
+      _cm2WarnStrFn 'Could not set screen mode. Will try again next login';
+      _cm2WarnFn;
+    fi
+    return;
+  fi
+
+  # Check nag count
+  if ! _nag_msg="$(
+    _testNagCountFn 'check' "${_nag_name}" "${_warn_nag_count}"
+  )"; then
+    _cm2SucStrFn 'View count limit reached.';
+    _cm2SucFn;
+    return;
+  fi
+
+  # If display refresh is not 60 Hz, and it is not 300 Hz, then it is 240 Hz.
+  # Warn about display bandwidth consumption.
+  _prompt_msg="$(cat <<EOF
+${_cm2HtmBeginStr}
+${_cm2HtmH3Str}${_title}</h3>
+
+${_cm2HtmPStr}The laptop display's refresh rate is currently set to<br>
+240 Hz. Higher refresh rates consume substantial<br>
+bandwidth, which may make it more difficult to use<br>
+multiple displays. If you encounter issues, consider<br>
+reducing the laptop display refresh rate to 60 Hz.</p>
+
+${_cm2HtmPStr}You may change the refresh rate using <code>System<br>
+Settings &gt; Display and Monitor &gt; Display<br>
+Configuration &gt; Refresh Rate</code>.</p>${_cm2HtmEndStr}
+
+${_cm2HtmPStr}This ${_nag_msg}.</p>
+EOF
+  )";
+  _cm2PromptUserFn "${_prompt_msg}" "${_win_title}";
+  _testNagCountFn 'inc' "${_nag_name}";
+  _cm2SucFn;
+}
+## . END _chkDispRefreshFn }
+
 ## BEGIN _chkHwConfigFn {
 _chkHwConfigFn () {
   declare _title _win_title _reason_str _prompt_msg _ans_str _output_str;
@@ -885,7 +1015,7 @@ _EOH14
   ## . End: Update version string }
 
   ## Begin: Handle reboot if recommended {
-  if [ ${_do_reboot} = 'y' ]; then
+  if [ "${_do_reboot}" = 'y' ]; then
     _prompt_msg="$(cat <<_EOH15
 ${_cm2HtmBeginStr}
 ${_cm2HtmH3Str}REBOOT RECOMMENDED</h3>
@@ -1093,6 +1223,7 @@ _mainFn () {
   _cm2EchoFn "== BEGIN :      ${_rootTitle}\n";
   _announceStartFn;
   _chkNvPMizerFn;       #5423
+  _chkDispRefreshFn;
   _chkBtrfsSetUpFn;
   _chkOemMultiDiskFn;
   _chkHwConfigFn;
@@ -1128,7 +1259,7 @@ declare _parentCmdStr _lookupList \
   _fixIbusExe _kcleanExe _resetEffectsExe _rollbackBackendExe \
   _rollbackSetExe _chainHelperExe _sysVersStr;
 
-_parentCmdStr="$(ps -o comm= $PPID)";
+_parentCmdStr="$(ps -o comm= "$PPID")";
 
 # These names are used only for DNS lookups as a means to confirm the internet
 # is working. FocusRx does not ping, connect to, or otherwise communicate with
