4128 Add name.url file support

diff --git a/package-main/usr/lib/kfocus/bin/kfocus-open-url-file b/package-main/usr/lib/kfocus/bin/kfocus-open-url-file
--- a/package-main/usr/lib/kfocus/bin/kfocus-open-url-file
+++ b/package-main/usr/lib/kfocus/bin/kfocus-open-url-file
@@ -10,7 +10,8 @@ _mainFn () {
   if [ -n "${_open_exe}" ]; then
     exec "${_open_exe}" "${_solve_url}";
   else
-    echo 'Could not run xdg-open' 1>&2 ;
+    echo 'Could not run xdg-open' 1>&2;
+    exit 3;
   fi
 }
 ## . END _mainFn }
