main/24.04.29~beta2, settings/24.04.13~beta2

diff --git a/package-settings/debian/kfocus-settings.postinst b/package-settings/debian/kfocus-settings.postinst
--- a/package-settings/debian/kfocus-settings.postinst
+++ b/package-settings/debian/kfocus-settings.postinst
@@ -222,7 +222,6 @@ fi
 ## . END Run kfocus-reset-effects to populate kfocus/kf5-settings
 
 ## BEGIN Set default SDDM theme
-#
 _sddmSetFile='/var/lib/kfocus/kfocus_sddm_theme_set'
 _sddmConfigFile='/etc/sddm.conf.d/kde_settings.conf'
 mkdir -p '/etc/sddm.conf.d';
@@ -270,19 +269,35 @@ fi
 ## . END Set default SDDM theme
 
 ## BEGIN Set DKMS autoinstall_all_kernels option
-#
 _dkmsFrameworkConfFile='/etc/dkms/framework.conf';
 _dkmsAutoinstallStr='autoinstall_all_kernels="yes"';
-mkdir -p '/etc/dkms';
-if ! [ -e "${_dkmsFrameworkConfFile}" ]; then
-  echo "${_dkmsAutoinstallStr}" > "${_dkmsFrameworkConfFile}";
-elif [ -f "${_dkmsFrameworkConfFile}" ]; then
-  if ! grep -q '^\s*autoinstall_all_kernels=' "${_dkmsFrameworkConfFile}";
-    then echo "${_dkmsAutoinstallStr}" >> "${_dkmsFrameworkConfFile}";
+# shellcheck disable=SC2043,SC2034
+for _idx in 1; do
+  mkdir -p '/etc/dkms' || {
+    _msg='warn: |/etc/dkms| exists but is not a directory ';
+    _msg+='or a link to a directory';
+    1>&2 echo "${_msg}";
+    break;
+  }
+
+  if ! [ -e "${_dkmsFrameworkConfFile}" ]; then
+    echo "${_dkmsAutoinstallStr}" > "${_dkmsFrameworkConfFile}" \
+      || 1>&2 echo "warn: could not write |${_dkmsFrameworkConfFile}|";
+    break;
   fi
-else
-  1>&2 echo "warn: |${_dkmsFrameworkConfFile}| exists but is not a file";
-fi
+
+  if [ -f "${_dkmsFrameworkConfFile}" ]; then
+    if ! grep -q '^\s*autoinstall_all_kernels=' "${_dkmsFrameworkConfFile}";
+      then echo "${_dkmsAutoinstallStr}" >> "${_dkmsFrameworkConfFile}" \
+        || 1>&2 echo "warn: could not append |${_dkmsFrameworkConfFile}|";
+    fi
+    break;
+  fi
+
+  _msg="warn: |${_dkmsFrameworkConfFile}| exists but is not a file ";
+  _msg+="or a link to a file";
+  1>&2 echo "${_msg}";
+done
 ## . END Set DKMS autoinstall_all_kernels option
 
 # Tag to allow some debhelper commands to inject relevant code
