6563 more porting to 26.04

diff --git a/package-settings/debian/kfocus-settings.postinst b/package-settings/debian/kfocus-settings.postinst
--- a/package-settings/debian/kfocus-settings.postinst
+++ b/package-settings/debian/kfocus-settings.postinst
@@ -269,35 +269,37 @@ fi
 ## . END Set default SDDM theme
 
 ## BEGIN Set DKMS autoinstall_all_kernels option
-_dkmsFrameworkConfFile='/etc/dkms/framework.conf';
-_dkmsAutoinstallStr='autoinstall_all_kernels="yes"';
+# Obsolete as of Ubuntu 26.04, 'autoinstall_all_kernels="yes"' is set by
+# upstream.
+#_dkmsFrameworkConfFile='/etc/dkms/framework.conf';
+#_dkmsAutoinstallStr='autoinstall_all_kernels="yes"';
 # shellcheck disable=SC2043,SC2034
-for _idx in 1; do
-  mkdir -p '/etc/dkms' || {
-    _msg='warn: |/etc/dkms| exists but is not a directory ';
-    _msg+='or a link to a directory';
-    1>&2 echo "${_msg}";
-    break;
-  }
-
-  if ! [ -e "${_dkmsFrameworkConfFile}" ]; then
-    echo "${_dkmsAutoinstallStr}" > "${_dkmsFrameworkConfFile}" \
-      || 1>&2 echo "warn: could not write |${_dkmsFrameworkConfFile}|";
-    break;
-  fi
-
-  if [ -f "${_dkmsFrameworkConfFile}" ]; then
-    if ! grep -q '^\s*autoinstall_all_kernels=' "${_dkmsFrameworkConfFile}";
-      then echo "${_dkmsAutoinstallStr}" >> "${_dkmsFrameworkConfFile}" \
-        || 1>&2 echo "warn: could not append |${_dkmsFrameworkConfFile}|";
-    fi
-    break;
-  fi
-
-  _msg="warn: |${_dkmsFrameworkConfFile}| exists but is not a file ";
-  _msg+="or a link to a file";
-  1>&2 echo "${_msg}";
-done
+#for _idx in 1; do
+#  mkdir -p '/etc/dkms' || {
+#    _msg='warn: |/etc/dkms| exists but is not a directory ';
+#    _msg+='or a link to a directory';
+#    1>&2 echo "${_msg}";
+#    break;
+#  }
+#
+#  if ! [ -e "${_dkmsFrameworkConfFile}" ]; then
+#    echo "${_dkmsAutoinstallStr}" > "${_dkmsFrameworkConfFile}" \
+#      || 1>&2 echo "warn: could not write |${_dkmsFrameworkConfFile}|";
+#    break;
+#  fi
+#
+#  if [ -f "${_dkmsFrameworkConfFile}" ]; then
+#    if ! grep -q '^\s*autoinstall_all_kernels=' "${_dkmsFrameworkConfFile}";
+#      then echo "${_dkmsAutoinstallStr}" >> "${_dkmsFrameworkConfFile}" \
+#        || 1>&2 echo "warn: could not append |${_dkmsFrameworkConfFile}|";
+#    fi
+#    break;
+#  fi
+#
+#  _msg="warn: |${_dkmsFrameworkConfFile}| exists but is not a file ";
+#  _msg+="or a link to a file";
+#  1>&2 echo "${_msg}";
+#done
 ## . END Set DKMS autoinstall_all_kernels option
 
 # Tag to allow some debhelper commands to inject relevant code
