4013 create and integrate rollback.2.source, fix bugs

diff --git a/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set b/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set
--- a/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set
+++ b/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set
@@ -11,7 +11,7 @@
 #              | labelAptSnapshot | labelUserSnapshot <username>
 #              | finalizeRestore  | trimSnapshots | prepareSystem
 #              | getBtrfsStatus   | restoreSnapshot (snapshot_id)
-#              | takeSnapshot
+#              | systemSnapshot
 # Purpose  : Performs snapshot management operations
 # Example  : kfocus-rollback-set restoreSnapshot @1234
 # License  : GPLv2
@@ -21,38 +21,60 @@
 #
 set -u;
 
-## BEGIN _importCommonFn {
-# Summary   : _importCommonFn
-# Purpose   : Load common routines, prefer relative dir
-# Example   : _importCommonFn;
-# Arguments : none
-# Globals   : Package vars _baseDir _baseName
-# Outputs   : none
-# Returns   : none
+_stderrFn () {
+  2>&1 echo "${_baseName} $*";
+}
+## BEGIN _loadLibTableFn {
+# Summary : _loadLibTableFn <lib_str1> <lib_str2> ...
+# Example : _loadLibTableFn "lib01:/usr/lib/lib01" "lib02";
+# Purpose :
+#   Import table of libs, one arg per lib.
+#     * Each arg can have alternates delimited by colons ':'
+#     * Fails if all alternates for a lib fails.
+#     * Starting lib string '#:' means the following libs are optional.
+#     * Diagnostics are sent to STDERR.
+#     * Libs without a directory use ${_binDir} as the path
 #
-_importCommonFn () {
-  declare _lib_list _is_loaded _lib_file;
-  _lib_list=(
-    "${_binDir}/common.2.source"
-    '/usr/lib/kfocus/lib/common.2.source'
-  );
-  _is_loaded='n';
-  for _lib_file in "${_lib_list[@]}"; do
-    if [ -r "${_lib_file}" ]; then
-      # shellcheck source=/usr/lib/kfocus/lib/common.2.source
-      if source "${_lib_file}"; then
+_loadLibTableFn () {
+  declare _lib_table _lib_list _lib_line _raw_path _lib_file _is_loaded;
+  _lib_table=("$@");
+
+  ## Begin: Iterate over lib lines.
+  for _lib_line in "${_lib_table[@]}"; do
+    # Split line into alternates.
+    #   Note: Echo removes trailing newline.
+    readarray -d: -t _lib_list < <(echo -n "${_lib_line}");
+    _is_loaded='n';
+
+    ## Begin: Iterate over alternates.
+    for _raw_path in "${_lib_list[@]}"; do
+      [ -z "$(dirname "${_raw_path}")" ] \
+        && _lib_file="${_binDir}/${_raw_path}" \
+        || _lib_file="${_raw_path}";
+
+      # shellcheck disable=SC1090
+      if ! [ -r "${_lib_file}" ]; then
+        _stderrFn "warn: source |${_lib_file}| not readable.";
+      elif source "${_lib_file}"; then
         _is_loaded='y';
         break;
-      fi
-    fi
-  done
+      else
+        _stderrFn "${_baseName} Error: source |${_lib_file}| is non-zero.";
+        return 1;
+      fi  
+    done
+    ## . End: Iterate over alternates.
 
-  if [ "${_is_loaded}" = 'n' ]; then
-    echo 1>&2 "${_baseName}: ABORT - Cannot source common lib";
-    exit 202;
-  fi
+    if [ "${_is_loaded}" != 'y' ]; then
+      _stderrFn "${_baseName} error: no lib loaded";
+      return 1;
+    fi  
+  done
+  ## . End: Iterate over lib lines.
+
+  return;
 }
-## . END _importCommonFn }
+## . END _loadLibTableFn }
 
 ## BEGIN Define error and exit handling {
 _trapExitFn () {
@@ -291,7 +313,8 @@ _prepareSystemFn () {
 }
 
 _restoreSnapshotFn () {
-  declare _target_snapshot _snapshot_path _boot_snapshot_path;
+  declare _target_snapshot _snapshot_path _boot_snapshot_path \
+    _snapshot_disp_id;
 
   _target_snapshot="${1:-}";
   if [ -z "${_target_snapshot}" ]; then
@@ -312,6 +335,8 @@ _restoreSnapshotFn () {
     _exitERR 'Expected snapshot path does not exist';
   fi
 
+  _snapshot_disp_id="$(_rb2MakeSnapshotDispIdFn "${_target_snapshot}")";
+
   mv '/btrfs_main/@' '/btrfs_main/@kfocus-rollback-working' || _exitCRIT;
   btrfs subvolume snapshot "${_snapshot_path}" '/btrfs_main/@' || _exitEMERG;
   # Failing to unmount /boot/efi before attempting to move the old subvol
@@ -325,7 +350,8 @@ _restoreSnapshotFn () {
   mount /boot/efi || _exitALERT;
 
   # Let the user know that a restore has completed
-  touch /btrfs_main/@/var/lib/kfocus/kfocus_rollback_restore_complete \
+  echo "${_snapshot_disp_id}" \
+    > /btrfs_main/@/var/lib/kfocus/kfocus_rollback_restore_complete \
     || _exitALERT;
 }
 
@@ -464,7 +490,7 @@ _systemRollbackFn () {
   _restoreSnapshotFn "${1:-}" || exit;
 }
 
-_takeSnapshotFn () {
+_systemSnapshotFn () {
   _createSnapshotFn "${1:-}" || _exitERR 'Could not create snapshot';
   _trimSnapshotsFn           || _exitERR 'Could not trim snapshots';
 }
@@ -523,8 +549,8 @@ _mainFn () {
 ## . END _mainFn }
 
 ## BEGIN Declare and assign global vars {
-declare _binName _binDir _baseName _baseDir _lockFile _btrfsStatus _browStr \
-  _erowStr _tableStr _prepareFailMsg _lowDiskMsg _inconsistentMsg \
+declare _binName _binDir _baseName _baseDir _lockFile _btrfsStatus _libTable \
+  _browStr _erowStr _tableStr _prepareFailMsg _lowDiskMsg _inconsistentMsg \
   _isPreparingSystem _snapshotMainDir _snapshotBootDir;
 
 _snapshotMainDir='/btrfs_main/@kfocus-rollback-snapshots';
@@ -543,8 +569,13 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   _lockFile="/tmp/kfocus-rollback-backend.lock";
   _btrfsStatus='';
 
-  # Import libs and assign more global vars
-  _importCommonFn;
+  # Import libs
+  _libTable=(
+    '/usr/lib/kfocus/lib/common.2.source'
+    '/usr/lib/kfocus/lib/rollback.2.source'
+  );
+
+  _loadLibTableFn "${_libTable[@]}" || exit 1;
 
   # Set error messages
   _browStr='<tr><td style="padding:8px 32px 8px 0">';
diff --git a/package-rollback/usr/lib/kfocus/bin/kfocus-snapshot b/package-rollback/usr/lib/kfocus/bin/kfocus-snapshot
--- a/package-rollback/usr/lib/kfocus/bin/kfocus-snapshot
+++ b/package-rollback/usr/lib/kfocus/bin/kfocus-snapshot
@@ -14,117 +14,67 @@
 #
 set -u;
 
-## BEGIN _importCommonFn {
-# Summary   : _importCommonFn
-# Purpose   : Load common routines, prefer relative dir
-# Example   : _importCommonFn;
-# Arguments : none
-# Globals   : Package vars _baseDir _baseName
-# Outputs   : none
-# Returns   : none
+_stderrFn () {
+  2>&1 echo "${_baseName} $*";
+}
+## BEGIN _loadLibTableFn {
+# Summary : _loadLibTableFn <lib_str1> <lib_str2> ...
+# Example : _loadLibTableFn "lib01:/usr/lib/lib01" "lib02";
+# Purpose :
+#   Import table of libs, one arg per lib.
+#     * Each arg can have alternates delimited by colons ':'
+#     * Fails if all alternates for a lib fails.
+#     * Starting lib string '#:' means the following libs are optional.
+#     * Diagnostics are sent to STDERR.
+#     * Libs without a directory use ${_binDir} as the path
 #
-_importCommonFn () {
-  declare _lib_list _is_loaded _lib_file;
-  _lib_list=(
-    "${_baseDir}/lib/common.2.source"
-    "${_binDir}/common.2.source"
-    '/usr/lib/kfocus/lib/common.2.source'
-  );
-  _is_loaded='n';
-  for _lib_file in "${_lib_list[@]}"; do
-    if [ -r "${_lib_file}" ]; then
-      # shellcheck source=/usr/lib/kfocus/lib/common.2.source
-      if source "${_lib_file}"; then
+_loadLibTableFn () {
+  declare _lib_table _lib_list _lib_line _raw_path _lib_file _is_loaded;
+  _lib_table=("$@");
+
+  ## Begin: Iterate over lib lines.
+  for _lib_line in "${_lib_table[@]}"; do
+    # Split line into alternates.
+    #   Note: Echo removes trailing newline.
+    readarray -d: -t _lib_list < <(echo -n "${_lib_line}");
+    _is_loaded='n';
+
+    ## Begin: Iterate over alternates.
+    for _raw_path in "${_lib_list[@]}"; do
+      [ -z "$(dirname "${_raw_path}")" ] \
+        && _lib_file="${_binDir}/${_raw_path}" \
+        || _lib_file="${_raw_path}";
+
+      # shellcheck disable=SC1090
+      if ! [ -r "${_lib_file}" ]; then
+        _stderrFn "warn: source |${_lib_file}| not readable.";
+      elif source "${_lib_file}"; then
         _is_loaded='y';
         break;
+      else
+        _stderrFn "${_baseName} Error: source |${_lib_file}| is non-zero.";
+        return 1;
       fi
+    done
+    ## . End: Iterate over alternates.
+
+    if [ "${_is_loaded}" != 'y' ]; then
+      _stderrFn "${_baseName} error: no lib loaded";
+      return 1;
     fi
   done
+  ## . End: Iterate over lib lines.
 
-  if [ "${_is_loaded}" = 'n' ]; then
-    echo 1>&2 "${_baseName}: ABORT - Cannot source common lib";
-    exit 202;
-  fi
+  return;
 }
-## . END _importCommonFn }
-
-## BEGIN _getSnapshotListStrFn {
-#
-_getSnapshotListStrFn () {
-   find '/btrfs_main/@kfocus-rollback-snapshots' -maxdepth 1 \
-     | cut -d'@' -f3 \
-     | sort -n -r \
-     | sed '/^$/d; s/^/@/;';
-}
-## . END _getSnapshotListStrFn }
-
-## BEGIN _makeSnapshotDispIdFn {
-#
-_makeSnapshotDispIdFn () {
-  declare _snapshot_id _snapshot_reason_loc _snapshot_reason_raw \
-    _snapshot_reason _snapshot_datetime _snapshot_disp_id;
-
-  _snapshot_id="${1:-}";
-  _snapshot_reason_loc="${2:-}";
-
-  if [ -z "${_snapshot_id}" ] || [ -z "${_snapshot_reason_loc}" ]; then
-    _cm2WarnStrFn 'Invalid arguments, cannot generate snapshot display ID';
-    return 1;
-  fi
-
-  _snapshot_reason_raw="$(cat "${_snapshot_reason_loc}")";
-  case "${_snapshot_reason_raw}" in
-    'Apt')
-      _snapshot_reason='Before Package Change';
-      ;;
-    'Timed')
-      _snapshot_reason='System Schedule';
-      ;;
-    'Pre-Rollback')
-      _snapshot_reason='Pre-Rollback';
-      ;;
-    *) # must be user-generated
-      _snapshot_reason="Created by ${_snapshot_reason_raw}";
-      ;;
-  esac
-
-  _snapshot_datetime="$(date -d "${_snapshot_id}" '+%a %F %H:%M')";
-
-  _snapshot_disp_id="${_snapshot_datetime} | ${_snapshot_reason}";
-  echo "${_snapshot_disp_id}";
-}
-## . END _makeSnapshotDispIdFn }
-
-_getBtrfsStatusFn () {
-  "${_snapshotSetExe}" 'getBtrfsStatus';
-}
-
-_takeSnapshotFn () {
-  "${_escExe}" "${_snapshotSetExe}" 'takeSnapshot' "${1:-}";
-}
+## . END _loadLibTableFn }
 
 ## BEGIN _mainFn {
 #
 _mainFn () {
   declare _btrfs_status_str _ans _exit_int _snapshot_id _snapshot_disp_id;
 
-  # This function will exit with LOCK if the lockfile cannot be grabbed, so we
-  # wait until the lock is released before showing the UI (since we have to in
-  # order to get the state of the system).
-  while true; do
-    _btrfs_status_str="$(_getBtrfsStatusFn)"
-    _exit_int="$?";
-
-    # Override false positive due to complex exit code handling
-    # shellcheck disable=SC2181
-    if [ "${_exit_int}" = "${_LOCK}" ]; then
-      sleep 1;
-    elif [ "${_exit_int}" = "${_NOTICE}" ]; then
-      break;
-    else
-      exit "${_exit_int}";
-    fi
-  done
+  _btrfs_status_str="$(_rb2GetBtrfsStatusFn)"
 
   if [ "${_btrfs_status_str}" != 'SUPPORTED, SET UP' ]; then
     _cm2PromptUserFn "${_systemUnsupportedMsg}" "${_winTitle}";
@@ -134,12 +84,11 @@ _mainFn () {
   _ans="$(_cm2PromptUserFn "${_createSnapshotMsg}" "${_winTitle}" 'a')";
 
   if [ "${_ans}" = 'y' ]; then
-    _takeSnapshotFn "$USER";
+    _rb2SystemSnapshotFn "$USER";
     _exit_int="$?";
     if [ "${_exit_int}" = "${_NOTICE}" ]; then
-      _snapshot_id="$(_getSnapshotListStrFn | head -n1)";
-      _snapshot_disp_id="$(_makeSnapshotDispIdFn "${_snapshot_id}" \
-        "/btrfs_main/@kfocus-rollback-snapshots/${_snapshot_id}/var/lib/kfocus/kfocus_rollback_snapshot_reason")";
+      _snapshot_id="$(_rb2GetSnapshotListStrFn | head -n1)";
+      _snapshot_disp_id="$(_rb2MakeSnapshotDispIdFn "${_snapshot_id}")";
       _snapshotCreatedMsg="${_snapshotCreatedMsg//XXX_SNAPSHOT_NAME_XXX/${_snapshot_disp_id}}";
       _cm2PromptUserFn "${_snapshotCreatedMsg}" "${_winTitle}";
     else
@@ -158,11 +107,10 @@ _mainFn () {
 ## . END _mainFn }
 
 ## BEGIN Declare and assign global vars {
-declare _binName _binDir _baseName _baseDir _assignList _kdiagExe \
+declare _binName _binDir _baseName _baseDir _assignList _libTable _kdiagExe \
   _whiptailExe _snapshotSetExe _escExe _winTitle _browStr _erowStr _tableStr \
   _createSnapshotMsg _systemUnsupportedMsg _snapshotCreatedMsg \
-  _snapshotCreationFailedMsg _criticalErrorMsg _NOTICE _ERR _CRIT _ALERT \
-  _EMERG _LOCK;
+  _snapshotCreationFailedMsg _criticalErrorMsg;
 ## . END Declare and assign global vars }
 
 ## BEGIN Run mainFn when script is NOT sourced {
@@ -173,13 +121,20 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   _baseDir="$(  dirname  "${_binDir}"  )" || exit 101;
   _baseName="$( basename "${_binName}" )" || exit 101;
 
+  # Import libs and assign more global vars
+  _libTable=(
+    '/usr/lib/kfocus/lib/common.2.source'
+    '/usr/lib/kfocus/lib/rollback.2.source'
+  );
+
+  _loadLibTableFn "${_libTable[@]}" || exit 1;
+
   _assignList=(
     '_kdiagExe|/usr/bin/kdialog'
     '_whiptailExe|/usr/bin/whiptail'
     "_snapshotSetExe|${_binDir}/kfocus-rollback-set"
   );
 
-  # Import libs and assign more global vars
   _importCommonFn;
   if ! _cm2AssignExeVarsFn "${_assignList[@]}"; then
     _cm2ErrStrFn 'Could not assign variable';
@@ -281,14 +236,6 @@ for instructions on how to safeguard your data.${_erowStr}</table>
 ${_cm2HtmEndStr}
 EOF
   )";
-
-  # Set meaningful names for error codes
-  _NOTICE='0';
-  _ERR='1';
-  _CRIT='2';
-  _ALERT='3';
-  _EMERG='4';
-  _LOCK='20';
 
   # Make sure TTY mode looks nice
   _cm2SetCliTypeFn 'whiptail'
