Overhaul BTRFS optimize architecture, fix bugs

diff --git a/package-rollback/usr/lib/kfocus/bin/kfocus-btrfs-optimize b/package-rollback/usr/lib/kfocus/bin/kfocus-btrfs-optimize
--- a/package-rollback/usr/lib/kfocus/bin/kfocus-btrfs-optimize
+++ b/package-rollback/usr/lib/kfocus/bin/kfocus-btrfs-optimize
@@ -2,19 +2,21 @@
 #
 # Copyright 2019-2024 MindShare Inc.
 #
-# Written for the Kubuntu Focus by M. Mikowski and A. Rainbolt
+# Written for the Kubuntu Focus by M. Mikowski and A. Rainbolt.
 #
 # Name     : kfocus-btrfs-optimize
-# Summary  : kfocus-btrfs-optimize (maintain | deepClean)
-# Purpose  : Performs maintenance and disk cleanup for KFocus systems using
-#            BTRFS.
+# Summary  : kfocus-btrfs-optimize
+# Purpose  : Provides a UI for optimizing the system BTRFS filesystems
 # Example  : kfocus-btrfs-optimize
 # License  : GPLv2
-# Run By   : kfocus-focusrx, kfocus-focusrx-system
+# Run By   : Users
 # Spec     : 4201
 #
 set -u;
 
+_stderrFn () {
+  2>&1 echo "${_baseName} $*";
+}
 ## BEGIN _loadLibTableFn {
 # Summary : _loadLibTableFn <lib_str1> <lib_str2> ...
 # Example : _loadLibTableFn "lib01:/usr/lib/lib01" "lib02";
@@ -67,287 +69,38 @@ _loadLibTableFn () {
 }
 ## . END _loadLibTableFn }
 
-## BEGIN Define error and exit handling {
-#
-_trapExitFn () {
-  1>&2 echo "${_baseName} was interrupted";
-  rm "${_lockFile}" || true;
-}
-
-_chkSetFlockFn () {
-  exec 211>"${_lockFile}" || exit 21;
-  if ! flock -n -e 211; then
-    _exitLOCK "Cannot get lock on ${_lockFile}";
-  fi
-  # Trap unexpected exits to clean up lock file
-  trap _trapExitFn EXIT;
-}
-
-_exitCleanFn () {
-  declare _int;
-  _int="$(_cm2EchoIntFn "${1:-0}")";
-  trap '' EXIT;
-  rm "${_lockFile}" || true;
-  exit "${_int}";
-}
-
-_exitWithCodeFn () {
-  declare _int _msg;
-
-  _int="$(_cm2EchoIntFn "${1:-0}")";
-  _msg="${2:-}";
-
-  if [ -n "${_msg}" ]; then
-    1>&2 echo "${_msg}";
-  fi
-  _exitCleanFn "${_int}";
-}
-
-_exitNOTICE () { _exitWithCodeFn  0 "$@"; }
-_exitERR ()    { _exitWithCodeFn  1 "$@"; }
-_exitCRIT ()   { _exitWithCodeFn  2 "$@"; }
-_exitALERT ()  { _exitWithCodeFn  3 "$@"; }
-_exitEMERG ()  { _exitWithCodeFn  4 "$@"; }
-_exitLOCK ()   { _exitWithCodeFn 20 "$@"; }
-## . END Define error and exit handling }
-
-## BEGIN _checkRootFn {
-#
-_checkRootFn () {
-  if [ "$UID" = '0' ]; then
-    return 0;
-  else
-    _cm2WarnStrFn 'This action requires root privileges.';
-    return 1;
-  fi
-}
-## . END _checkRootFn }
-
-## BEGIN _getMainUsageReportFn {
-#
-_getMainUsageReportFn () {
-  LC_ALL='C' "${_btrfsExe}" filesystem usage -b '/btrfs_main';
-}
-## . END _getMainUsageReportFn }
-
-## BEGIN _getBootUsageReportFn {
-#
-_getBootUsageReportFn () {
-  LC_ALL='C' "${_btrfsExe}" filesystem usage -b '/btrfs_boot';
-}
-## . END _getBootUsageReportFn }
-
-## BEGIN _getMainBtduReportFn {
-#
-_getMainBtduReportFn () {
-  LC_ALL='C' "${_btduExe}" --du --min-resolution=1M --headless '/btrfs_main'
-}
-## . END _getMainBtduReportFn }
-
-## BEGIN _getMainFragReportFn {
-#
-_getMainFragReportFn () {
-  "${_filefragExe}" '/btrfs_main/@';
-}
-## . END _getMainFragReportFn }
-
-## BEGIN _balanceMainFn {
-#
-_balanceMainFn () {
-  declare _main_report _main_unallocd _main_free _old_report _last_unallocd \
-    _last_free _trigger_threshold
-
-  _trigger_threshold=1073741824; # 1 GiB
-
-  _main_report="$(_getMainUsageReportFn)";
-  _main_unallocd="$(grep $'Device unallocated:\t' <<< "${_main_report}" \
-    | awk '{ print $3 }')";
-  _main_free="$(grep $'Free (estimated):\t' <<< "${_main_report}" \
-    | awk '{ print $3 }')";
-  _last_unallocd=-1;
-  _last_free=0;
-
-  if [ -f "${_optimizeStatePath}" ]; then
-    _old_report="$(cat "${_optimizeStatePath}")";
-    _last_unallocd="$(grep 'unallocd' <<< "${_old_report}" | cut -d'|' -f2)";
-    _last_free="$(grep 'free' <<< "${_old_report}" | cut -d'|' -f2)";
-  fi
-
-  if (( (_last_unallocd - _main_unallocd) >= "${_trigger_threshold}" )) \
-    || (( (_main_free - _last_free) >= "${_trigger_threshold}" )); then
-    "${_btrfsBalanceExe}" -u 85 '/btrfs_main';
-    echo "unallocd|${_main_unallocd}" > "${_optimizeStatePath}";
-    echo "free|${_main_free}" >> "${_optimizeStatePath}";
-  fi
-}
-## . END _balanceMainFn }
-
-## BEGIN _balanceBootFn {
-#
-_balanceBootFn () {
-  "${_btrfsBalanceExe}" -u 85 '/btrfs_boot';
-}
-## . END _balanceBootFn }
-
-## BEGIN _spaceReclaimFn {
-#
-_spaceReclaimFn () {
-  declare _big_threshold _deep_clean_yn _btdu_report _report_val_list \
-    _report_file_list _clean_file_list _report_idx _current_file _file_size;
-
-  _big_threshold=10737418240; # 10 GiB
-  _deep_clean_yn="${1:-n}";
-
-  _btdu_report="$(
-    _getMainBtduReportFn \
-      | grep '<UNREACHABLE>' \
-      | sort -nr \
-      | sed 's|/<SINGLE>/<DATA>/<UNREACHABLE>||; /<ERROR>/d'
-  )";
-
-  readarray -t _report_val_list  < <(cut -f1 <<< "${_btdu_report}");
-  readarray -t _report_file_list < <(cut -f2 <<< "${_btdu_report}");
-
-  _clean_file_list=();
-  for (( _report_idx=0; _report_idx < ${#_report_val_list[@]}; \
-    _report_idx++ )); do
-    _current_file="${_report_file_list[_report_idx]}"
-
-    if [ -f "${_current_file}" ]; then
-      _file_size="$(du -b "${_current_file}" | cut -f1)";
-      _unreachable_size="${_report_val_list[_report_idx]}";
-      
-      if [ "${_deep_clean_yn}" = 'y' ]; then
-        if [ "$(bc -l <<< "scale=2; \
-           (${_unreachable_size} / ${_file_size}) > 0.05")" \
-           = '1' ]; then
-          _clean_file_list+=( "${_current_file}" );
-        fi
-      else
-        if (( _file_size < _big_threshold )); then
-          if [ "$(bc -l <<< "scale=2; \
-             (${_unreachable_size} / ${_file_size}) > 0.15")" \
-             = '1' ]; then
-            _clean_file_list+=( "${_current_file}" );
-          fi
-        else
-          if [ "$(bc -l <<< "scale=2; \
-             (${_unreachable_size} / ${_file_size}) > 0.30")" \
-             = '1' ]; then
-            _clean_file_list+=( "${_current_file}" );
-          fi
-        fi
-      fi
-    fi
-  done
-
-  if [ "${_deep_clean_yn}" = 'y' ]; then
-    if (( ${#_clean_file_list[@]} > 50 )); then
-      _clean_file_list=( "${_clean_file_list[@]:0:50}" );
-    fi
-  else
-    if (( ${#_clean_file_list[@]} > 10 )); then
-      _clean_file_list=( "${_clean_file_list[@]:0:10}" );
-    fi
-  fi
-
-  "${_reclaimExe}" "${_clean_file_list[@]}";
-}
-## . END _spaceReclaimFn }
-
-## BEGIN _defragmentFn {
-#
-_defragmentFn () {
-  declare _frag_report _frag_count_list _target_frag_list _file_list \
-    _defrag_file_list _report_idx;
-
-  _frag_report="$(
-    _getMainFragReportFn \
-    | sort -nr;
-  )";
-  
-  readarray -t _frag_count_list  < <(cut -d'|' -f2 <<< "${_frag_report}");
-  readarray -t _target_frag_list < <(cut -d'|' -f3 <<< "${_frag_report}");
-  readarray -t _file_list        < <(cut -d'|' -f4 <<< "${_frag_report}");
-
-  _defrag_file_list=();
-  for (( _report_idx=0; _report_idx < ${#_file_list[@]}; \
-    _report_idx++ )); do
-    _current_file="${_file_list[_report_idx]}";
-
-    if [ -f "${_current_file}" ]; then
-      if (( _frag_count_list[_report_idx] > \
-        _target_frag_list[_report_idx] )); then
-        _defrag_file_list+=( "${_current_file}" );
-      fi
-    fi
-  done
-
-  if (( ${#_defrag_file_list[@]} > 50 )); then
-    _defrag_file_list=( "${_defrag_file_list[@]:0:50}" );
-  fi
-
-  if [ "${#_defrag_file_list[@]}" -gt 0 ]; then
-    "${_btrfsExe}" filesystem defragment "${_defrag_file_list[@]}";
-  fi
-}
-## . END _defragmentFn }
-
-## BEGIN _deleteAllSnapshotsFn {
-# NOTICE: You must run kfocus-btrfs-optimize AS ROOT for this function to
-# succeed. For security purposes, this is intentionally NOT part of
-# kfocus-btrfs-optimize-set.
-#
-_deleteAllSnapshotsFn () {
-  declare _snapshot_list _current_snapshot;
-
-  readarray -t _snapshot_list < <(
-    _cm2LsFn '/btrfs_main/@kfocus-rollback-snapshots' 2>/dev/null
-  );
-
-  if [ "${#_snapshot_list[@]}" = '0' ] || [ -z "${_snapshot_list[0]}" ]; then
-    _cm2WarnStrFn 'No snapshots found.';
-    return 1;
-  fi
-
-  for _current_snapshot in "${_snapshot_list[@]}"; do
-    "${_snapshotSetExe}" deleteSnapshot "${_current_snapshot}";
-  done
-}
-
 ## BEGIN _mainFn {
 #
 _mainFn () {
-  declare _mode;
+  declare _btrfs_status_str _ans _exit_int;
 
-  _chkSetFlockFn;
+  _btrfs_status_str="$(_rb2GetBtrfsStatusFn)"
 
-  _mode="${1:-}";
-  case "${_mode}" in
-    'maintain')
-      _checkRootFn   || exit;
-      _balanceMainFn || exit;
-      _balanceBootFn || exit;
-      _spaceReclaimFn;
-      ;;
-    'deepClean')
-      _checkRootFn       || exit;
-      _balanceMainFn 'y' || exit;
-      _balanceBootFn     || exit;
-      _spaceReclaimFn 'y';
-      _deleteAllSnapshotsFn;
-      _defragmentFn;
-      ;;
-    *) _cm2WarnStrFn  'Invalid mode specified.';;
+  if [ "${_btrfs_status_str}" != 'SUPPORTED, SET UP' ]; then
+    _cm2PromptUserFn "${_systemUnsupportedMsg}" "${_winTitle}";
+    exit "${_NOTICE}";
+  fi
 
-  esac
-  _exitCleanFn;
+  _ans="$(_cm2PromptUserFn "${_doOptimizeMsg}" "${_winTitle}" 'a')";
+
+  if [ "${_ans}" = 'y' ]; then
+    if _cm2RunLongCmdFn 'Optimizing the drive...' "${_optimizeSetExe}" \
+      'deepClean'; then
+      _cm2PromptUserFn "${_optimizeSuccessfulMsg}" "${_winTitle}";
+    else
+      _cm2PromptUserFn "${_optimizeFailedMsg}" "${_winTitle}" 's';
+    fi
+  fi
+
+  exit "${_NOTICE}";
 }
 ## . END _mainFn }
 
 ## BEGIN Declare and assign global vars {
-declare _userId _binName _binDir _baseName _baseDir _lockFile \
-  _optimizeStatePath;
+declare _binName _binDir _baseName _baseDir _assignList _libTable _kdiagExe \
+  _whiptailExe _optimizeSetExe _escExe _winTitle _browStr _erowStr _tableStr \
+  _systemUnsupportedMsg _doOptimizeMsg _optimizeSuccessfulMsg \
+  _optimizeFailedMsg;
 ## . END Declare and assign global vars }
 
 ## BEGIN Run mainFn when script is NOT sourced {
@@ -357,8 +110,6 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   _binDir="$(   dirname  "${_binName}" )" || exit 101;
   _baseDir="$(  dirname  "${_binDir}"  )" || exit 101;
   _baseName="$( basename "${_binName}" )" || exit 101;
-  _lockFile='/tmp/kfocus-btrfs-optimize.lock';
-  _optimizeStatePath='/var/lib/kfocus/last_optimize_state';
 
   # Import libs and assign more global vars
   _libTable=(
@@ -369,18 +120,90 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   _loadLibTableFn "${_libTable[@]}" || exit 1;
 
   _assignList=(
-    '_btrfsExe|/usr/bin/btrfs'
-    '_btrfsBalanceExe|/usr/bin/btrfs-balance-least-used'
-    '_btduExe|/usr/bin/btdu'
-    "_snapshotSetExe|${_binDir}/kfocus-rollback-set"
-    "_reclaimExe|${_binDir}/kfocus-btrfs-reclaim-space"
-    "_filefragExe|${_binDir}/kfocus-report-filefrag"
+    '_kdiagExe|/usr/bin/kdialog'
+    '_whiptailExe|/usr/bin/whiptail'
+    "_optimizeSetExe|${_binDir}/kfocus-btrfs-optimize-set"
   );
 
+  _importCommonFn;
   if ! _cm2AssignExeVarsFn "${_assignList[@]}"; then
     _cm2ErrStrFn 'Could not assign variable';
     exit 1;
   fi
+
+  _escExe="$(_cm2GetEscExeFn)" || exit;
+
+  # Set UI messages
+  _winTitle='Drive Optimizer';
+  _browStr='<tr><td style="padding:8px 32px 8px 0">';
+  _erowStr='</td></tr>';
+  _tableStr='<table style="width:100%;margin-right:32px">';
+
+  _systemUnsupportedMsg="$(cat <<EOF
+${_cm2HtmBeginStr}${_tableStr}
+${_browStr}<h3 style="color:#f7941d">System Unsupported</h3>${_erowStr}
+
+${_browStr}Doc: <a style="color:#1d99f3"
+href="https://kfocus.org/wf/tools#optimize"
+>https://kfocus.org/wf/tools#optimize</a>${_erowStr}
+
+${_browStr}This system does not appear to support<br>
+optimization.${_erowStr}</table>
+${_cm2HtmEndStr}
+EOF
+  )";
+
+  _doOptimizeMsg="$(cat <<EOF
+${_cm2HtmBeginStr}${_tableStr}
+${_browStr}<h3 style="color:#f7941d">Drive Optimizer</h3>${_erowStr}
+
+${_browStr}Doc: <a style="color:#1d99f3"
+  href="https://kfocus.org/wf/tools#optimize"
+  >https://kfocus.org/wf/tools#optimize</a>${_erowStr}
+
+${_browStr}Use this tool to optimize your system's boot<br>
+drive. This will delete all snapshots, defragment<br>
+highly fragmented files, free disk space that has<br>
+become unreachable, and ensure that your boot<br>
+drive's free space is properly organized.${_erowStr}
+
+${_browStr}<b>Optimize Drive Now?</b>${_erowStr}</table>
+${_cm2HtmEndStr}
+EOF
+  )";
+
+  _optimizeSuccessfulMsg="$(cat <<EOF
+${_cm2HtmBeginStr}${_tableStr}
+${_browStr}<h3 style="color:#f7941d">Drive Optimization Finished
+</h3>${_erowStr}
+
+${_browStr}Your system's boot drive has been optimized<br>
+successfully.${_erowStr}</table>
+${_cm2HtmEndStr}
+EOF
+  )";
+
+  _optimizeFailedMsg="$(cat <<EOF
+${_cm2HtmBeginStr}${_tableStr}
+${_browStr}<h3 style="color:#f7941d">Drive Optimization Failed</h3>${_erowStr}
+
+${_browStr}The drive optimization operation failed! This<br>
+incident may be the result of failing hardware<br>
+or a software conflict.${_erowStr}
+
+${_browStr}<b>Please do NOT reboot. Back up your data as<br>
+soon as possible.</b> Failure to do so may result in<br>
+data loss. See<br>
+<a style="color:#1d99f3"
+href="https://kfocus.org/wf/backup#bkm_take_a_snapshot"
+>https://kfocus.org/wf/backup#bkm_take_a_snapshot</a><br>
+for instructions on how to safeguard your data.${_erowStr}</table>
+${_cm2HtmEndStr}
+EOF
+  )";
+  
+  # Make sure TTY mode looks nice
+  _cm2SetCliTypeFn 'whiptail'
 
   _mainFn "$@";
 fi
diff --git a/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set b/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set
--- a/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set
+++ b/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-set
@@ -88,7 +88,8 @@ _trapExitFn () {
 _chkSetFlockFn () {
   exec 211>"${_lockFile}" || exit 21;
   if ! flock -n -e 211; then
-    _exitLOCK "Cannot get lock on ${_lockFile}";
+    1>&2 echo "Cannot get lock on ${_lockFile}";
+    exit 20;
   fi
   # Trap unexpected exits to clean up lock file
   trap _trapExitFn EXIT;
@@ -119,7 +120,6 @@ _exitERR ()    { _exitWithCodeFn  1 "$@"; }
 _exitCRIT ()   { _exitWithCodeFn  2 "$@"; }
 _exitALERT ()  { _exitWithCodeFn  3 "$@"; }
 _exitEMERG ()  { _exitWithCodeFn  4 "$@"; }
-_exitLOCK ()   { _exitWithCodeFn 20 "$@"; }
 ## . END Define error and exit handling }
 
 ## BEGIN _promptAllUsersFn {
@@ -521,7 +521,11 @@ _mainFn () {
     _exitERR;
   fi
 
-  _main_min_space=21474836480 # 20 GiB
+  (( _main_min_space = ( ( $(
+      LC_ALL='C' df / \
+        | tail -n1 \
+        | awk '{ print $2 }'
+    ) * 1024 ) / 100 ) * 15 ));
   _boot_min_space=1073741824 # 1 GiB
   _main_space="$(LC_ALL=C btrfs filesystem usage -b /btrfs_main \
     | awk '/Free \(estimated\)/{ print $3 }')";
@@ -613,8 +617,11 @@ ${_cm2HtmBeginStr}${_tableStr}
 ${_browStr}<h3 style="color:#f7941d">Low Disk Space</h3>${_erowStr}
 
 ${_browStr}Your system is running low on disk space. This could result in
-filesystem corruption if not corrected. Please clear some space
-by removing files or moving them to other drives.${_erowStr}
+filesystem corruption if not corrected. It is highly recommended
+that you use the Drive Optimizer to clear some space. You may also
+need to delete excess files or move them to other drives. You can
+access the Drive Optimizer by clicking <code>Start Menu >
+Kubuntu Focus Tools > Drive Optimizer</code>.${_erowStr}
 
 ${_browStr}For your safety, no snapshot-related actions have been
 performed.${_erowStr}</table>
