4534 Update rollback and rtests for beta testing

diff --git a/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-backend b/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-backend
--- a/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-backend
+++ b/package-rollback/usr/lib/kfocus/bin/kfocus-rollback-backend
@@ -13,7 +13,18 @@
 # Spec     : 4013
 #
 # Notice: 'Throws' below refers to the specific error functions
-#   that are called, e.g. _exitERR, that exit the script.
+# that are called, e.g. _exitERR, that exit the script, and points
+# to the exit function where this can occur.
+#
+# TODO: Many routines that used _exitXXX are wrapped in subshells to
+# capture STDOUT. Therefore, the exits are rarely used and are often
+# ignored. To audit this:
+#   1. Identify all routines that use _exitXXX
+#   2. Identify all uses of those routines
+#   3. To ensure proper exit from subshells, use the form:
+#    _str="$(_routineWithExitXXX)" || exit;
+# TODO: Make metadb writes and disk operations atomic with rollback.
+# TODO: Move all exit calls to top-level logic, not low-level calls.
 #
 # shellcheck source=../lib/common.2.source
 # shellcheck source=../lib/rollback.2.source
@@ -63,7 +74,7 @@ _loadLibTableFn () {
         && _lib_file="${_binDir}/${_raw_path}" \
         || _lib_file="${_raw_path}";
 
-      # shellcheck disable=SC1090
+      # shellcheck disable=SC1090,SC1094
       if ! [ -r "${_lib_file}" ]; then
         _logWrapFn 'warn' "Source |${_lib_file}| not readable.";
       elif source "${_lib_file}"; then
@@ -107,8 +118,8 @@ _trapExitFn () {
 # Arguments : none
 # Globals   : _lockDir, lockFile, _trapExitFn
 # Outputs   : Messages to STDERR
-# Returns   : 21 - Lock file permission denied
-#           : 20 - Cannot get lock
+# Returns   : 1 - Cannot get lock; recoverable by waiting
+#           : 2 - Unrecoverable error
 #           : 0 - Success
 # Throws    : none
 #
@@ -134,12 +145,13 @@ _chkSetFlockFn () {
 ## . END _chkSetFlockFn }
 
 ## BEGIN _exitCleanFn {
+# Summary   : _exitCleanFn <_int>;
 # Purpose   : Unset traps for exit and then do so.
-# Example   : _exitCleanFn;
-# Arguments : none
+# Example   : _exitCleanFn 1;
+# Arguments : <_int>
 # Globals   : _cm2*
 # Outputs   : none
-# Returns   : Exit code
+# Returns   : Exit code <_int>
 # Throws    : none
 #
 _exitCleanFn () {
@@ -161,6 +173,7 @@ _exitCleanFn () {
 # Arguments :
 #   _int - Exit code. This maps different than standard syslog levels
 #          (TODO: Bring this closer to standard 0-7 syslog levels?)
+#          (Consider prefix to syslog, e.g. 40=emerg, 41=alert, etc)
 #   _msg - Message for syslog
 # Globals   : _cm2*
 # Outputs   : Writes to syslog
@@ -168,21 +181,37 @@ _exitCleanFn () {
 # Throws    : none
 #
 _exitWithCodeFn () {
-  declare _int _msg;
+  declare _int _msg _do_call_stack _key _stack_str;
 
   _int="$(_cm2EchoIntFn "${1:-0}")";
   _msg="${2:-}";
+  _do_call_stack='n';
+  
+  case ${_int} in
+    '0') _key='notice';;
+    '1') _key='err'   ;;
+    '2') _key='crit'  ;;
+    '3') _key='alert' ;;
+    '4') _key='emerg' ;;
+  esac
 
-  if [ -n "${_msg}" ]; then
-    1>&2 echo "${_msg}";
-    case ${_int} in
-      '0') _cm2LogFn 'notice' "${_msg}";;
-      '1') _cm2LogFn 'err'    "${_msg}";;
-      '2') _cm2LogFn 'crit'   "${_msg}";;
-      '3') _cm2LogFn 'alert'  "${_msg}";;
-      '4') _cm2LogFn 'emerg'  "${_msg}";;
-    esac
+  if [ "$$" != "$BASHPID" ]; then
+    _key='alert';
+    _logWrapFn "${_key}" 'exitWithCodeFn is run in a subshell!';
+    _do_call_stack='y';
+  elif [ "${_int}" != '0' ]; then
+    _do_call_stack='y';
   fi
+  
+  if [ -n "${_msg}" ]; then
+    _logWrapFn "${_key}" "${_msg}";
+  fi
+
+  if [ "${_do_call_stack}" = 'y' ]; then
+    _stack_str="$(_cm2EchoStackFn 2>&1)";
+    _logWrapFn "${_key}" "Call Stack: ${_stack_str}";
+  fi
+
   _exitCleanFn "${_int}";
 }
 ## . END _exitWithCodeFn }
@@ -236,13 +265,7 @@ _promptAllUsersFn () {
 
 ## BEGIN _checkRootFn {
 _checkRootFn () {
-  declare _uid;
-  _uid="$(id -u)";
-  if [ "${_uid}" = '0' ]; then
-    return 0;
-  else
-    return 1;
-  fi
+  [ "$(id -u)" = 0 ];
 }
 ## . END _checkRootFn }
 
@@ -259,21 +282,21 @@ _checkRootFn () {
 #
 _clearRestoreFn () {
   _checkBtrfsStatusSetUpFn;
-  # TODO: Throw a serious error here if cannot remove
-  rm -f "${_rb2RestoreCompleteFile}" || true;
-  _cm2LogFn 'notice' 'Restore flag cleared.';
+  rm -f "${_rb2RestoreCompleteFile}" \
+    || _exitERR "Could not remove |${_rb2RestoreCompleteFile}|";
+  _logWrapFn 'notice' 'Restore flag cleared.';
 }
 ## . END _clearRestoreFn }
 
 ## BEGIN _readMetadbFn {
-# Summary   : _readMetadbFn _group_key _val_key
+# Summary   : _readMetadbFn _group_str _key_str
 # Purpose   : Reads a value from the kfocus-rollback snapshot metadata
 #             database (metadb).
 # Example   : _readMetadbFn '@1234' 'name'
 # Arguments :
-#   _group_key - The data group in which the value should be found.
+#   _group_str - The data group in which the value should be found.
 #      Often, our groups are named after snapshot IDs, e.g. '@1234'.
-#   _val_key - The key associated with the desired data.
+#   _key_str - The key associated with the desired data.
 #   IMPORTANT: If either a group or key does not exist, an empty string
 #     is returned. It is NOT an error condition. This routine also
 #     creates an empty metadb file if it does not already exist.
@@ -285,12 +308,10 @@ _clearRestoreFn () {
 # Throws    : none
 #
 _readMetadbFn () {
-  # We intentionally do not check the BTRFS state here as _checkBtrfsStatusFn
-  # has to read the metadb.
-  declare _group_key _val_key _err_msg;
+  declare _group_str _key_str _err_msg;
 
-  _group_key="${1:-}";
-  _val_key="${2:-}";
+  _group_str="${1:-}";
+  _key_str="${2:-}";
   _err_msg='Cannot read metadb: ';
 
   if ! [ -d "${_rb2MainDir}" ]; then
@@ -298,11 +319,11 @@ _readMetadbFn () {
     return 1;
   fi
 
-  [ -n "${_group_key}" ] || {
+  [ -n "${_group_str}" ] || {
     _logWrapFn 'err' "${_err_msg} No group string provided.";
     return 1;
   }
-  [ -n "${_val_key}" ] || {
+  [ -n "${_key_str}" ] || {
     _logWrapFn 'err' "${_err_msg} No key string provided.";
     return 1;
   }
@@ -310,12 +331,9 @@ _readMetadbFn () {
   if [ -f "${_snapshotMetaDb}" ]; then
     "${_kreadconfig5Exe}" \
       --file "${_snapshotMetaDb}" \
-      --group "${_group_key}" \
-      --key "${_val_key}" \
-      || {
-        _logWrapFn 'err' "${_err_msg} No val for |${_group_key}:${_val_key}|";
-        return 1;
-      }
+      --group "${_group_str}" \
+      --key "${_key_str}" \
+      || _exitALERT "${_err_msg} |${_group_str}:${_key_str}|";
   elif [ -e "${_snapshotMetaDb}" ]; then
     _logWrapFn 'err' "${_err_msg} Metadb is not a regular file.";
     return 1;
@@ -328,64 +346,68 @@ _readMetadbFn () {
 ## . END _readMetadbFn }
 
 ## BEGIN _writeMetadbFn {
-# Summary   : _writeMetadbFn _group_key _val_key _val_str
+# Summary   : _writeMetadbFn _group_str _key_str _val_str
 # Purpose   : Writes a value to or deletes a value from the kfocus-rollback
 #             snapshot metadata database (metadb).
 # Example   : _writeMetadbFn '@1234' 'name' 'bmV3IG5hbWU='
 # Arguments :
-#   _group_key - The data group in which the value should be written.
+#   _group_str - The data group in which the value should be written.
 #      Often, our groups are named after snapshot IDs, e.g. '@1234'.
-#   _val_key       - The key to associate with the provided data.
+#   _key_str       - The key to associate with the provided data.
 #   _val_str   - The string to be stored. If blank, delete the key.
 # Globals   : _snapshotMetaDb
 # Outputs   : none
 # Returns   : 0 on success, 1 on failure
-# Throws    : none
+# Throws    : _exitALERT if kwriteconfig5 fails.
+# Notice    :
+#   _writeMetadbFn exits ONLY on kwriteconfig5 error, others are ignored.
+#   This should probably be fixed.
 #
 _writeMetadbFn () {
-  declare _group_key _val_key _val_str _err_msg;
+  declare _group_str _key_str _val_str _err_msg _fail_msg _cmd_list;
 
-  _group_key="${1:-}";
-  _val_key="${2:-}";
+  _group_str="${1:-}";
+  _key_str="${2:-}";
   _val_str="${3:-}";
-  _err_msg='Cannot write metadb: ';
+  _err_msg='Cannot write to metadb: ';
 
   if ! [ -d "${_rb2MainDir}" ]; then
-    _logWrapFn 'err' "${_err_msg} No main dir |${_rb2MainDir}|";
+    _wrapLogFn 'err' "${_err_msg} No main dir |${_rb2MainDir}|";
     return 1;
   fi
 
-  [ -n "${_group_key}" ] || {
-    _logWrapFn 'err' "${_err_msg} No group string provided.";
+  if [ -z "${_group_str}" ]; then
+    _wrapLogFn 'err' "${_err_msg} No group string provided.";
     return 1;
-  }
-  [ -n "${_val_key}" ] || {
-    _logWrapFn 'err' "${_err_msg} No key provided.";
-    return 1;
-  }
+  fi
+
+  if [ -z "${_key_str}" ]; then
+    _wrapLogFn 'err' "${_err_msg} No key string provided.";
+  fi
 
   if ! [ -e "${_snapshotMetaDb}" ]; then
     touch "${_snapshotMetaDb}";
     chmod '0644' "${_snapshotMetaDb}";
   elif ! [ -f "${_snapshotMetaDb}" ] ; then
-    _logWrapFn 'err' "${_err_msg} metadb is not a regular file.";
+    _wrapLogFn 'err' "${_err_msg} Not a regular file.";
     return 1;
   fi
 
+  _cmd_list=( "${_kwriteconfig5Exe}"
+    '--file'  "${_snapshotMetaDb}"
+    '--group' "${_group_str}"
+    '--key'    "${_key_str}"
+  );
+
   if [ -z "${_val_str}" ]; then
-    "${_kwriteconfig5Exe}" \
-      --file "${_snapshotMetaDb}" \
-      --group "${_group_key}" \
-      --key "${_val_key}" --delete \
-      || _exitALERT 'Failed to delete metadb key!';
+    _cmd_list+=( '--delete' );
+    _fail_msg="Failed to delete key |${_key_str}|";
   else
-    "${_kwriteconfig5Exe}" \
-      --file "${_snapshotMetaDb}" \
-      --group "${_group_key}" \
-      --key "${_val_key}" \
-      "${_val_str}" \
-      || _exitALERT 'Failed to write metadb key!';
+    _cmd_list+=( "${_val_str}" );
+    _fail_msg="Failed to write |${_key_str}:${_val_str}|";
   fi
+
+  "${_cmd_list[@]}" || _exitALERT "${_err_msg} ${_fail_msg}";
 }
 ## . END _writeMetadbFn }
 
@@ -428,7 +450,7 @@ _getManualSwitchStateBackendFn () {
 #             _ERR - _getManualSwitchStateBackendFn state not MANUAL or AUTO.
 #
 _getManualSwitchStateFn () {
-  # Both exit on failure per Throws above.
+  # Both exit on failure per "Throws", above.
   _checkBtrfsStatusSetUpFn;
   _getManualSwitchStateBackendFn;
 }
@@ -448,7 +470,7 @@ _getManualSwitchStateFn () {
 # Throws    :
 #   _NOTICE - _checkBtrfsStatusSetUpFn or _checkRootFn check failed.
 #   _ALERT  - _writeMetaDbFn when it cannot save.
-#   _ERR - No argument provided, invalid argument provided, or the specified
+#   _ERR    - No argument provided, invalid argument provided, or the specified
 #     switch state is the same as the current switch state.
 #
 _setManualSwitchStateFn () {
@@ -472,7 +494,7 @@ _setManualSwitchStateFn () {
       if [ "${_current_state_str}" = 'AUTO' ]; then
         _exitERR 'Cannot change manual switch state to existing state!';
       else
-        # This exits on failure, SOMETIMES. TODO: Fix this.
+        # See _writeMetadbFn note on return and exit behavior
         _writeMetadbFn 'global' 'manualSwitchState' 'AUTO';
       fi
       ;;
@@ -481,7 +503,7 @@ _setManualSwitchStateFn () {
       if [ "${_current_state_str}" = 'MANUAL' ]; then
         _exitERR 'Cannot change manual switch state to existing state!';
       else
-        # This exits on failure, SOMETIMES. TODO: Fix this.
+        # See _writeMetadbFn note on return and exit behavior
         _writeMetadbFn 'global' 'manualSwitchState' 'MANUAL';
       fi
       ;;
@@ -537,9 +559,6 @@ _getMainFragReportFn () {
 #     the disk becomes corrupted or the user does something wrong.
 # Returns   : none
 # Throws    : none
-#
-# TODO: Use this gauntlet code AFTER A-B unit testing and ensure
-#   match to existing and expected logic
 #
 _readMainFsFn () {
   LC_ALL='C' mount | grep btrfs | grep ' on / ' \
@@ -945,7 +964,7 @@ _prepareSystemFn () {
   ## . END STAGE 5: Finish additional mounts }
 
   _isPreparingSystem='n';
-  _cm2LogFn 'notice' 'System successfully prepared for snapshotting.';
+  _logWrapFn 'notice' 'System successfully prepared for snapshotting.';
 }
 ## . END _prepareSystemFn }
 
@@ -1001,12 +1020,13 @@ _deleteSnapshotFn () {
   fi
 
   # Ensure any and all snapshot metadata is deleted
+  # See _writeMetadbFn note on return and exit behavior
   _writeMetadbFn "${_target_snapshot_id}" 'name' '';
   _writeMetadbFn "${_target_snapshot_id}" 'desc' '';
   _writeMetadbFn "${_target_snapshot_id}" 'pinned' '';
   _writeMetadbFn "${_target_snapshot_id}" 'reason' '';
 
-  _cm2LogFn 'notice' "Snapshot ${_target_snapshot_id} deleted.";
+  _logWrapFn 'notice' "Snapshot ${_target_snapshot_id} deleted.";
 }
 ## . END _deleteSnapshotFn }
 
@@ -1052,7 +1072,7 @@ _finalizeRestoreFn () {
   else
     _exitERR 'Cannot finalize restore, restore operation half-done!';
   fi
-  _cm2LogFn 'notice' 'Restore operation successfully finalized.';
+  _logWrapFn 'notice' 'Restore operation successfully finalized.';
 }
 ## . END _finalizeRestoreFn }
 
@@ -1093,7 +1113,7 @@ _trimSnapshotsFn () {
     if ! [[ " ${_boot_snapshot_list[*]} " \
       =~ [[:space:]]${_snapshot_id}[[:space:]] ]]; then
       _deleteSnapshotFn "${_snapshot_id}";
-      _cm2LogFn 'warning' \
+      _logWrapFn 'warning' \
         "Mismatched BTRFS snapshot ${_snapshot_id} trimmed from main.";
     fi
   done
@@ -1103,7 +1123,7 @@ _trimSnapshotsFn () {
     if ! [[ " ${_main_snapshot_list[*]} " \
       =~ [[:space:]]${_snapshot_id}[[:space:]] ]]; then
       _deleteSnapshotFn "${_snapshot_id}";
-      _cm2LogFn 'warning' \
+      _logWrapFn 'warning' \
         "Mismatched BTRFS snapshot ${_snapshot_id} trimmed from boot.";
     fi
   done
@@ -1136,7 +1156,7 @@ _trimSnapshotsFn () {
     done
   fi
 
-  _cm2LogFn 'notice' \
+  _logWrapFn 'notice' \
     "Snapshots trimmed, deleting ${_delete_count} non-mismatched snapshots.";
 }
 ## . END _trimSnapshotsFn }
@@ -1234,7 +1254,7 @@ _createSnapshotFn () {
   esac
 
   # Save snapshot creation reason in the metadata database.
-  # This exits on failure, SOMETIMES. TODO: Fix this.
+  # See _writeMetadbFn note on return and exit behavior
   _writeMetadbFn "@${_timestamp_str}" 'reason' "${_snapshot_event_type}";
 
   # Snapshot and sync main and boot filesystems
@@ -1248,7 +1268,7 @@ _createSnapshotFn () {
     || _exitEMERG 'Failed to sync boot filesystem!';
   sync;
 
-  _cm2LogFn 'notice' "Snapshot @${_timestamp_str} created.";
+  _logWrapFn 'notice' "Snapshot @${_timestamp_str} created.";
 }
 ## . END _createSnapshotFn }
 
@@ -1333,7 +1353,7 @@ _getSnapshotReasonFn () {
   # Migrate reason to metadb if stored old-style inside the snapshot
   if [ -z "${_snapshot_reason_raw}" ]; then
     _snapshot_reason_raw="$(cat "${_snapshot_reason_file}")";
-    # This exits on failure, SOMETIMES. TODO: Fix this.
+    # See _writeMetadbFn note on return and exit behavior
     _writeMetadbFn "${_snapshot_id}" 'reason' "${_snapshot_reason_raw}";
   fi
 
@@ -1505,7 +1525,7 @@ _restoreSnapshotFn () {
   # Trim older snapshots
   _trimSnapshotsFn || _exitALERT 'Unable to trim snapshots post-restore!';
 
-  _cm2LogFn 'notice' "Snapshot ${_target_snapshot_id} restored.";
+  _logWrapFn 'notice' "Snapshot ${_target_snapshot_id} restored.";
 }
 ## . END _restoreSnapshotFn }
 
@@ -1638,7 +1658,7 @@ _setSnapshotMetadataFn () {
   fi
 
   # Write snapshot name, description, pin status to snapshot metadb
-  # This exits on failure, SOMETIMES. TODO: Fix this.
+  # See _writeMetadbFn note on return and exit behavior
   _writeMetadbFn "${_snapshot_id}" 'name' "${_name_str}";
   _writeMetadbFn "${_snapshot_id}" 'desc' "${_desc_str}";
   _writeMetadbFn "${_snapshot_id}" 'pinned' "${_is_pinned}";
@@ -1699,7 +1719,8 @@ _balanceMainFn () {
   # Balance if conditions met
   if [ "${_do_balance}" = 'y' ]; then
     # Balance main fs
-    "${_btrfsBalanceExe}" -u "${_balance_percent}" "${_rb2MainDir}" || return;
+    "${_btrfsBalanceExe}" -u "${_balance_percent}" "${_rb2MainDir}" \
+      || _exitALERT 'Could not balance main BTRFS filesystem!';
 
     # Save new unallocated and free space data to state file
     _main_report="$(_getMainUsageReportFn)";
@@ -1707,13 +1728,14 @@ _balanceMainFn () {
       | awk '{ print $3 }')";
     _main_free_int="$(grep $'Free (estimated):\t' <<< "${_main_report}" \
       | awk '{ print $3 }')";
-  # This exits on failure, SOMETIMES. TODO: Fix this.
+
+    # See _writeMetadbFn note on return and exit behavior
     _writeMetadbFn 'global' 'lastUnallocInt' "${_main_unalloc_int}";
     _writeMetadbFn 'global' 'lastFreeInt' "${_main_free_int}";
 
-    _cm2LogFn 'notice' "Main filesystem balanced.";
+    _logWrapFn 'notice' "Main filesystem balanced.";
   else
-    _cm2LogFn 'notice' \
+    _logWrapFn 'notice' \
       "Main filesystem not balanced: not forced and threshold not met.";
   fi
 }
@@ -1735,7 +1757,7 @@ _balanceBootFn () {
   # Unconditionally balance boot space
   "${_btrfsBalanceExe}" -u 85 "${_rb2BootDir}" || return;
 
-  _cm2LogFn 'notice' 'Boot filesystem balanced.';
+  _logWrapFn 'notice' 'Boot filesystem balanced.';
 }
 ## . END _balanceBootFn }
 
@@ -1771,13 +1793,13 @@ _deleteAllSnapshotsFn () {
   # Delete each snapshot, unpinning if needed
   for _current_snapshot in "${_snapshot_list[@]}"; do
     if [ "$(_readMetadbFn "${_current_snapshot}" 'pinned')" = 'y' ]; then
-      # This exits on failure, SOMETIMES. TODO: Fix this.
+      # See _writeMetadbFn note on return and exit behavior
       _writeMetadbFn "${_current_snapshot}" 'pinned' 'n';
     fi
     _deleteSnapshotFn "${_current_snapshot}";
   done
 
-  _cm2LogFn 'notice' "All snapshots deleted.";
+  _logWrapFn 'notice' 'All snapshots deleted.';
 }
 ## . END _deleteAllSnapshotsFn }
 
@@ -1889,7 +1911,7 @@ _defragmentFn () {
       || return;
   fi
 
-  _cm2LogFn 'notice' \
+  _logWrapFn 'notice' \
     "Defragmented ${#_defrag_file_list[@]} files on main filesystem.";
 }
 ## . END _defragmentFn }
@@ -1914,7 +1936,7 @@ _btrfsMaintainFn () {
   _checkBtrfsStatusSetUpFn;
   _balanceMainFn 'n' || _exitALERT  'Failed to balance main filesystem!';
   _balanceBootFn     || _exitALERT  'Failed to balance boot filesystem!';
-  _cm2LogFn 'notice' "Routine BTRFS maintenance complete.";
+  _logWrapFn 'notice' "Routine BTRFS maintenance complete.";
 }
 ## . END _btrfsMaintainFn }
 
@@ -1943,7 +1965,7 @@ _btrfsDeepCleanFn () {
   _balanceMainFn 'y' || _exitALERT 'Failed to balance main filesystem!';
   _balanceBootFn     || _exitALERT 'Failed to balance boot filesystem!';
   _defragmentFn      || _exitALERT 'Failed to defragment files!';
-  _cm2LogFn 'notice' "BTRFS deep clean operation complete.";
+  _logWrapFn 'notice' "BTRFS deep clean operation complete.";
 }
 ## . END _btrfsDeepCleanFn }
 
@@ -2061,8 +2083,8 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
     exit 1;
   fi
 
-  _cm2SetLogLevelFn 'warn'; # Syslog all issues warn or greater
-  _cm2SetLogTagFn 'kfocus-rollback-backend';
+  _cm2SetLogLevelFn 'notice'; # Syslog all issues notice or greater
+  _cm2SetLogTagFn "${_baseName}";
 
   # Set error messages
   _browStr='<tr><td style="padding:8px 32px 8px 0">';
